---
- name: Install cfssl Docker image
  hosts: all
  vars:
    cfssl_version: v1.4.1
    checkout_dir: /tmp/cfssl-checkout
  tasks:
    - git:
        repo: https://github.com/cloudflare/cfssl.git
        dest: "{{ checkout_dir }}"
        version: "{{ cfssl_version }}"
        depth: 1
    - command:
        cmd: "docker build . -t cloudflare-cfssl:{{ cfssl_version }}"
        chdir: "{{ checkout_dir }}"
    - file:
        path: "{{ checkout_dir }}"
        state: absent
