name: 'Terraform test for Network module of Azure Example'
on:
  pull_request:
    branches:
      - master
    paths:
      - 'modules/azure/network/**'
      - 'modules/universal/bastion/**'
      - 'modules/universal/name-generator/**'
      - 'examples/azure/network/**'
      - 'provision/ansible/**'
  push:
    branches:
      - master
    paths:
      - 'modules/azure/network/**'
      - 'modules/universal/bastion/**'
      - 'modules/universal/name-generator/**'
      - 'examples/azure/network/**'
      - 'provision/ansible/**'
jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      TF_VERSION: 0.12.19
      TF_ACTIONS_COMMENT: true
      TF_TEST_WORKING_DIR: ./examples/azure/network
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: 'Terraform Format'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_subcommand: 'fmt'
          tf_actions_working_dir: ${{ env.TF_TEST_WORKING_DIR }}
          tf_actions_version: ${{ env.TF_VERSION }}
          tf_actions_comment: ${{ env.TF_ACTIONS_COMMENT }}
      - name: 'Terraform Init'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_subcommand: 'init'
          tf_actions_working_dir: ${{ env.TF_TEST_WORKING_DIR }}
          tf_actions_version: ${{ env.TF_VERSION }}
          tf_actions_comment: ${{ env.TF_ACTIONS_COMMENT }}
      - name: 'Terraform Validate'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_subcommand: 'validate'
          tf_actions_working_dir: ${{ env.TF_TEST_WORKING_DIR }}
          tf_actions_version: ${{ env.TF_VERSION }}
          tf_actions_comment: ${{ env.TF_ACTIONS_COMMENT }}
